# Generated by Django 3.1.5 on 2021-01-14 10:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': '회원', 'verbose_name_plural': '회원정보'},
        ),
    ]
