# Generated by Django 3.1.5 on 2021-01-14 10:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dista', '0002_auto_20210114_1905'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ('-created',), 'verbose_name': '작성된 댓글', 'verbose_name_plural': '모든 댓글'},
        ),
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ('-created',), 'verbose_name': '작성된 포스트', 'verbose_name_plural': '모든 포스트'},
        ),
    ]
